name: RegrowthSMP
version: '1.0.0'
main: org.lushplugins.regrowthsmp.RegrowthSMP
api-version: '1.21'
softdepend:
  - Animatronics
  - ExcellentCrates
commands:
  regrowthsmp:
    usage: /regrowthsmp
  givecosmetic:
    usage: /givecosmetic
  recipes:
    usage: /recipes
  abilities:
    usage: /abilities
  function:
    usage: /function
  timer:
    usage: /timer
  spawnpinata:
    usage: /spawnpinata
  schedule:
    usage: /schedule
  withdelayedtime:
    usage: /withdelayedtime